### ISSUE TITLE
System Exclusive messages not being received by MIDI input

### ISSUE THREAD

**Issue by randomtestsubject** [86Box/86Box#1181]
**Describe the bug**
MIDI System Exclusive Messages are not being received by 86Box's MIDI input while other MIDI messages are.

**To Reproduce**
Steps to reproduce the behavior (no special hardware needed):
1. Install any virtual MIDI cable under Windows 10 (loopMIDI, LoopBe, etc.)
2. Route the virtual MIDI cable from any application in Windows capable of sending MIDI to a MIDI capable program running under 86Box, by selecting the virtual MIDI cable as 86Box's MIDI In, configuring 86Box to emulate a standalone MPU-401, and setting the receiving program to use the MPU if necessary.
3. Send notes or controller data to the program in 86Box to confirm MIDI data is being received.
4. Send system exclusive data (any hex string beginning with F0 and ending with F7)

**Expected behavior**
Reception of system exclusive data over the MIDI port

**Screenshots**
Some screenshots:

![image](https://user-images.githubusercontent.com/73717762/102664443-64d40780-4148-11eb-9049-454c2d9e8ad5.png)

![image](https://user-images.githubusercontent.com/73717762/102664471-77e6d780-4148-11eb-92c5-772128efa541.png)

![image](https://user-images.githubusercontent.com/73717762/102664505-892fe400-4148-11eb-981e-a2be0e006cfd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - 86Box version: v2.10 build 2573
 - Build type: for this example, optimized

**Additional context**
This apparent blockage or filtering of sysex is persistent between regular and optimized builds over time, appears to affect both MPU and SB MIDI, regardless of guest operating system or or other system configurations. This example is from Win98 but I have attempted to make this work under MS-DOS with old MIDI sequencers that receive sysex (Cakewalk, Sequencer Plus, PowerTracks Pro) with no success.

**Comment by OBattler** [comment]
Since we have switched to the RTMIDI library not that long ago, can you please test if the problem still occurs?

**Comment by dhrdlicka** [comment]
> Hello, happy to test! Unfortunately I'm unable to get any MIDI messages into the latest 86Box at all, even just a simple Note On. Set things up in the usual way, and tried with both MPU and Sound Blaster. Is MIDI input confirmed working in the new version?

Does the problem occur on the v3.0 stable release?

**Comment by OBattler** [comment]
Can you test and see which build exactly completely broke MIDI input?

**Comment by OBattler** [comment]
Also, a fix for obtaining the MIDI input device has just been selected, see if it fixes MIDI input.

**Comment by randomtestsubject** [comment]
Hi, tested with builds 3377, 3400 as before, and the new 3416 (thanks for that) - no MIDI input appears to be received.

Version 3.0 build 3333 does receive MIDI notes. I tested further to see if it would receive system exclusive, and it did not.

**Comment by OBattler** [comment]
Yes, 3333 still had the old WinMM MIDI code.

In any case, I just committed another RTMIDI fix. See if this makes MIDI input work again.

Also, you can you upload the entire VM please (86box.cfg, NVR folder, and hard disk image) so I can test this stuff myself and try to further see where it may break (if it still does)?

**Comment by randomtestsubject** [comment]
I see, I noticed the MIDI devices do not have the numeric suffix in 3333 that appear now too.

I tested the new 3417 build and there was no change in result. I have attached a zip of the VM as requested, minus the contents of the rom directory, which uses the rom set from 12/23 on my setup:

[86Box-Windows-64-b3417-midi-test.zip](https://github.com/86Box/86Box/files/7822485/86Box-Windows-64-b3417-midi-test.zip)

A little about the VM: MS-DOS boots directly into the sequencer, which is highly keystroke driven. Two ways to see if MIDI input is working:

1) Press 'R' from the main screen (to arm Record) then '[space]' to start recording, if notes are recording the 'Mem' in the upper right will decrease each time one is received.

or 2) Press 'X' from the main screen (for XSETUP) then 'M' (for MIDI ANALYZER) - if there is any MIDI input of any kind across all 16 channels, this will display it.

EDIT: I always unzip the entire ROM set to use with 86Box. In preparing the VM to attach, I deleted all but the 486 ROM this machine uses (ali1429), along with all but VGA under video, to keep the upload under 25MB. I ran once after this to verify it would boot, went ahead and tested MIDI, and lo and behold, MIDI notes being recorded by the sequencer!

I then restored the complete set of machine ROMS, rebooted, and MIDI once again was not being received. It would appear there is something about having the complete set of machine ROMS present that prevents MIDI input from working.

I tested system exclusive once I found this issue, but no luck - sysex is still not being received.

**Comment by OBattler** [comment]
Try now, it should be fixed but it would be good if you made sure it is in fact fixed.

**Comment by randomtestsubject** [comment]
Happy to try, this did fix MIDI input out of the box, the issue of having to delete all but the selected machine ROM seems to be resolved. Note On/Off, CC, Pitch Bend, Aftertouch, all are received. However, System Exclusive messages still don't get through.

Attached is a screenshot of the sequencer's MIDI Analyzer in 86Box, side by side with SendSX monitoring the same MIDI Port - you can see the Note On/Off messages are received on both sides, but the small sysex strings are not.

![2022-01-07 07_48_17-Mail](https://user-images.githubusercontent.com/73717762/148554686-d0cdfa4d-a35f-445c-a3ae-6eb2096b77b0.png)

In my experience with this sequencer on real hardware, there were no special settings required to allow it to receive sysex. However, my MIDI interfaces were either MusicQuest or Opcode. I've never used it with a real MPU-401, so I can't be sure there wasn't some special configuration of the card needed. (Although I would think that Voyetra's VAPI drivers would have addressed this.) Perusing technical data of the MPU-401, it does appear there are commands that can be sent to the MPU that have to do with the passing of System Exclusive, but I'm not sure if those even apply to UART mode.

**Comment by ts-korhonen** [comment]
@randomtestsubject can you try the [latest build](https://ci.86box.net/job/86Box/3422/)? I should now pass sysex messages in uart mode.

**Comment by randomtestsubject** [comment]
Hi, unfortunately I'm getting the same result with the latest (3422) - all classes of MIDI data are seen in the MIDI monitor but sysex. I did a bit of digging to verify, the program only uses MPU in UART mode, if that helps.

**Comment by ts-korhonen** [comment]
Ok, I tried it with midi-ox both on host and guest (win98), and the messages was seen. I'll try to debug the program you're using next - I assume it's that dos one in the uploaded VM?

**Comment by ts-korhonen** [comment]
![image](https://user-images.githubusercontent.com/80648513/148603116-ef3dfbcd-8126-4863-9a63-dcf1d85f2b97.png)

Ok, so the commands do come through, but the software isn't displaying the sysex itself. This looks like the situation I had in midiox when I forgot to enable sysex from the menu.

**Comment by ts-korhonen** [comment]
Ok, it looks like the UART mode isn't detected correctly, fix incoming.

**Comment by ts-korhonen** [comment]
@randomtestsubject Can you test again to verify if it now works as expected with build 3424?

**Comment by randomtestsubject** [comment]
@ts-korhonen Yes, that appears to have fixed it, nicely done! In addition to the short message test in the screenshot, I was able to send a bulk dump from my Roland synth without any issues.

![2022-01-07 17_22_58-86Box v3 2  build 3424  - 101% -  ALi M1429  Olystar LIL1429 - i486DX2_40](https://user-images.githubusercontent.com/73717762/148619898-6929ce1f-d047-4a05-aae1-3d41a980dc7b.png)

**Comment by OBattler** [comment]
Good to hear that's now fixed. I guess this can be closed now then.

**Comment by randomtestsubject** [comment]
Really appreciate taking the time to look into this, thank you.
