### ISSUE TITLE
Voodoo-related issues

### ISSUE THREAD

**Issue by OBattler** [86Box/86Box#4483]
Tracking them here so they're all in one place:
- [ ] #6250 ;
- [ ] #5067 ;
- [ ] #4565 ;
- [ ] #4077 ;
- [ ] #2924 .

**Comment by unreal9010** [comment]
~A minor Voodoo 2-related issue to report:
In Shogo: Mobile Armour Division and Grim Fandango, two or three lines of white or black dots can be seen at the top of the screen when using a D3D renderer (any driver version from DX5 to D7).
This, however, doesn't happen with Voodoo Graphics or Banshee or Voodoo 3.~

**Comment by unreal9010** [comment]
More Voodoo 2-related issues:
~major slowdowns (down to 10%) can occur when entering or browsing the SAVE or LOAD menu in Grim Fandango (if Voodoo 2 is selected as the renderer), accessing Settings menu in Moto Racer or when opening the drop-down menu in Hardball 6.
Please note that these issues only occur when using Voodoo 2. When using any of the Banshee or Voodoo 3 cards slowdowns don't happen and menus can be browsed at 100% speed.~

~Another issue to report is related to Moto Racer 2. Currently, only the DX5 driver works with the game (demo and full version).  Using any other V2 driver causes the game to hang when starting a race. Not 100% sure whether this is a real behaviour or some kind of a bug. The game was released after the DX6 driver became available, not to mention EA had a tendency to encourage people to upgrade to the latest driver version so it would be awkward not to work with a commonly used driver.~

**Comment by jriwanek** [comment]
As you mentioned regression, could you tell us which prior 86Box version didn't have the problem?

**Comment by unreal9010** [comment]
I don't think any 86Box builds without these regressions actually exist. I tested various ODR/NDR builds released in the past years as well as PCem v14-17 builds and found out that regressions also happen with Voodoo Graphics. Turning off recompiler in Voodoo device options didn't help either.
For now, the only way to avoid these regressions is not to use Voodoo Graphics or Voodoo 2 as the rendering device.

**Comment by jriwanek** [comment]
Then I think you're confusing regressions and bugs, a regression would require it to have worked before, It's important to be clear on the difference so we're not wasting our time having to look over previous versions needlessly.

**Comment by unreal9010** [comment]
Correct. These slowdowns are bugs. My bad.

**Comment by unreal9010** [comment]
I also found out that they don't seem to be dynarec-related. I've just tested these 3 games with Via Cyrix III running at 166 Mhz and dynarec turned off and slowdowns still occur when the above mentioned menus are accessed (the games are otherwise running at 100%).

**Comment by OBattler** [comment]
Fixed: Extreme Assault DOS game Voodoo transparency glitch .

**Comment by OBattler** [comment]
In Shogo: Mobile Armour Division, Grim Fandango and a couple of other games, two or three lines of white (Shogo) or black (GF) dots can be seen at the top of the screen when using a D3D renderer (tested with any DX5-DX7 drivers available, including reference ones, Diamond and Creative).
The above doesn't happen with Voodoo Graphics, Voodoo Banshee or Voodoo 3. Unfortunately, I don't have a real Voodoo 2 at hand so I can't say with 100% certainty whether this is an 86Box or a Voodoo 2 bug, however, the same issue is also present in PCem (see picture).

![148678827-50130c78-ec6c-4d33-8c05-1ac816297b75](https://github.com/user-attachments/assets/c4fffa97-e0fe-4224-bce7-d7540f469d28)

**Comment by kkwpsv** [comment]
> In Shogo: Mobile Armour Division, Grim Fandango and a couple of other games, two or three lines of white (Shogo) or black (GF) dots can be seen at the top of the screen when using a D3D renderer (tested with any DX5-DX7 drivers available, including reference ones, Diamond and Creative).在《Shogo: Mobile Armor Division》、《Grim Fandango》和其他几款游戏中，使用 D3D 渲染器（使用任何 DX5 进行测试）时，可以在屏幕顶部看到两行或三行白色 (Shogo) 或黑色 (GF) 点- 提供 DX7 驱动程序，包括参考驱动程序、Diamond 驱动程序和 Creative 驱动程序）。 The above doesn't happen with Voodoo Graphics, Voodoo Banshee or Voodoo 3. Unfortunately, I don't have a real Voodoo 2 at hand so I can't say with 100% certainty whether this is an 86Box or a Voodoo 2 bug, however, the same issue is also present in PCem (see picture).Voodoo Graphics、Voodoo Banshee 或 Voodoo 3 不会出现上述情况。不幸的是，我手头没有真正的 Voodoo 2，所以我不能 100% 确定这是 86Box 还是 Voodoo 2 的 bug，然而，PCem 中也存在同样的问题（见图）。
> 
> ![148678827-50130c78-ec6c-4d33-8c05-1ac816297b75](https://private-user-images.githubusercontent.com/10365853/401636880-c4fffa97-e0fe-4224-bce7-d7540f469d28.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MTIwMzIsIm5iZiI6MTczNjUxMTczMiwicGF0aCI6Ii8xMDM2NTg1My80MDE2MzY4ODAtYzRmZmZhOTctZTBmZS00MjI0LWJjZTctZDc1NDBmNDY5ZDI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDEyMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNDY1MTY3ODE1Y2ExY2NlMzEyMWQ0Y2RmMDhiMTU0NjlhMmJlNGJmNjAyZGJmNWFlZWJhZWNlMjk3NWQ1ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XJy0AlNGllMqfFBFxEWxhzAigagmYjQaId1XWhq1-Po)


I have real Voodoo 1 / Voodoo 2 / Voodoo 3 Graphics card. I'm willing to help testing if you provide the game.

**Comment by unreal9010** [comment]
> > In Shogo: Mobile Armour Division, Grim Fandango and a couple of other games, two or three lines of white (Shogo) or black (GF) dots can be seen at the top of the screen when using a D3D renderer (tested with any DX5-DX7 drivers available, including reference ones, Diamond and Creative).在《Shogo: Mobile Armor Division》、《Grim Fandango》和其他几款游戏中，使用 D3D 渲染器（使用任何 DX5 进行测试）时，可以在屏幕顶部看到两行或三行白色 (Shogo) 或黑色 (GF) 点- 提供 DX7 驱动程序，包括参考驱动程序、Diamond 驱动程序和 Creative 驱动程序）。 The above doesn't happen with Voodoo Graphics, Voodoo Banshee or Voodoo 3. Unfortunately, I don't have a real Voodoo 2 at hand so I can't say with 100% certainty whether this is an 86Box or a Voodoo 2 bug, however, the same issue is also present in PCem (see picture).Voodoo Graphics、Voodoo Banshee 或 Voodoo 3 不会出现上述情况。不幸的是，我手头没有真正的 Voodoo 2，所以我不能 100% 确定这是 86Box 还是 Voodoo 2 的 bug，然而，PCem 中也存在同样的问题（见图）。
> > ![148678827-50130c78-ec6c-4d33-8c05-1ac816297b75](https://private-user-images.githubusercontent.com/10365853/401636880-c4fffa97-e0fe-4224-bce7-d7540f469d28.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MTIwMzIsIm5iZiI6MTczNjUxMTczMiwicGF0aCI6Ii8xMDM2NTg1My80MDE2MzY4ODAtYzRmZmZhOTctZTBmZS00MjI0LWJjZTctZDc1NDBmNDY5ZDI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDEyMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNDY1MTY3ODE1Y2ExY2NlMzEyMWQ0Y2RmMDhiMTU0NjlhMmJlNGJmNjAyZGJmNWFlZWJhZWNlMjk3NWQ1ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XJy0AlNGllMqfFBFxEWxhzAigagmYjQaId1XWhq1-Po)
> 
> I have real Voodoo 1 / Voodoo 2 / Voodoo 3 Graphics card. I'm willing to help testing if you provide the game.

That would be awesome. Here is a link to the Shogo demo:
https://www.moddb.com/games/shogo-mobile-armor-division/downloads/shogo-mobile-armor-division-demo

The above issue is present in both demo and full version of Shogo and doesn't affect other Voodoo cards. Thank you for your time.

**Comment by kkwpsv** [comment]
There's no white dots in real voodoo2.

The screenshot:
![Screenshot 2025-01-11 19-55-36](https://github.com/user-attachments/assets/08efea0b-a909-4039-a940-b79434e9d27a)

Voodoo 2 driver Info:
![Screenshot 2025-01-11 20-03-35](https://github.com/user-attachments/assets/0d60e0c2-7242-4ab8-9564-9bf7b958536a)


I use a Extron scalers and USB HDMI capture card to capture them.

**Comment by unreal9010** [comment]
Perfect!
Thank you for taking your time.
It can now be fully confirmed as a bug.

**Comment by lotharsm** [comment]
I'm currently observing issues when playing back MPEG2 encoded video using the Voodoo emulation. The issues can be replicated on the latest stable version and current nightly builds, I just tested with build 6500.

Playing back the video results in a completely wrong color palette. The issue doesn't seem to be related to the video playback software - I was able to replicate the problem on WinDVD and in a game that's using its own MPEG2 decoder.

Playback in WinDVD:
![Image](https://github.com/user-attachments/assets/5407fa38-355a-48a3-a48d-249c697c16c8)

Playback using custom decoder:
![Image](https://github.com/user-attachments/assets/ea60d8fb-8ccb-4d08-ba64-6b6fa43577ea)
![Image](https://github.com/user-attachments/assets/fda96823-c37b-44f5-a0c1-237adcf05271)

Right now, all available Voodoo cards show the same problem.

- Using different driver versions: no change
- NDR vs. ODR: no change
- Render threads (4, 2, 1): no change
- Dynarec for Voodoo enabled and disengaged: no change

Please let me know if you need more information.

Latest machine, video and voodoo configration:
```
[3Dfx Voodoo Graphics]
type = 2
framebuffer_memory = 2
texture_memory = 2
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

[Machine]
cpu_family = pentium_p55c
cpu_multi = 2.5
cpu_speed = 166666666
cpu_use_dynarec = 1
fpu_type = internal
machine = 5sg100
mem_size = 65536

[Video]
gfxcard = voodoo3_2k_agp
video_fullscreen_scale_maximized = 1
```

**Comment by Dizzy611** [comment]
Lots of stuff to do, not a lot of time to do it in. We're a small team, we work on bugs as we can and we're constantly fixing or improving things. The Voodoo 2 issues are known and are something we are working on. Please be patient, and please stop flooding our Discord with messages along these same lines asking when things will be fixed.

The general answer you're going to get on complicated volunteer open source projects like this to "When will X be fixed" is "When it's fixed.". 86Box is no different.

**Comment by MrPepka** [comment]
I also want to report a problem with 3dfx voodoo 3 3000 emulation (I use SFFT drivers). Namely, in the game Toy Story 2 textures stopped displaying correctly. Unfortunately, I am not able to determine from which build this problem occurs. I am attaching the cfg file and screenshots with this problem
https://mega.nz/file/xrJyRC4Y#TqgIfPJhwgBZnsNdj4kowa43UUvnh6beS6DukeSN4X8

![Image](https://github.com/user-attachments/assets/b7f1e851-11d8-4f18-99dc-70fd5a42e133)

**Comment by OBattler** [comment]
> I also want to report a problem with 3dfx voodoo 3 3000 emulation (I use SFFT drivers). Namely, in the game Toy Story 2 textures stopped displaying correctly. Unfortunately, I am not able to determine from which build this problem occurs. I am attaching the cfg file and screenshots with this problem https://mega.nz/file/xrJyRC4Y#TqgIfPJhwgBZnsNdj4kowa43UUvnh6beS6DukeSN4X8
> 
> ![Image](https://github.com/user-attachments/assets/b7f1e851-11d8-4f18-99dc-70fd5a42e133)

Please bisect - remember the last build where it worked, then test (that + latest) / 2, then if that works, test (that + latest) / 2, otherwise, test (last known good + that) / 2, and so on.

**Comment by OBattler** [comment]
> I'm currently observing issues when playing back MPEG2 encoded video using the Voodoo emulation. The issues can be replicated on the latest stable version and current nightly builds, I just tested with build 6500.
> 
> Playing back the video results in a completely wrong color palette. The issue doesn't seem to be related to the video playback software - I was able to replicate the problem on WinDVD and in a game that's using its own MPEG2 decoder.
> 
> Playback in WinDVD: ![Image](https://github.com/user-attachments/assets/5407fa38-355a-48a3-a48d-249c697c16c8)
> 
> Playback using custom decoder: ![Image](https://github.com/user-attachments/assets/ea60d8fb-8ccb-4d08-ba64-6b6fa43577ea) ![Image](https://github.com/user-attachments/assets/fda96823-c37b-44f5-a0c1-237adcf05271)
> 
> Right now, all available Voodoo cards show the same problem.
> 
>     * Using different driver versions: no change
> 
>     * NDR vs. ODR: no change
> 
>     * Render threads (4, 2, 1): no change
> 
>     * Dynarec for Voodoo enabled and disengaged: no change
> 
> 
> Please let me know if you need more information.
> 
> Latest machine, video and voodoo configration:
> 
> ```
> [3Dfx Voodoo Graphics]
> type = 2
> framebuffer_memory = 2
> texture_memory = 2
> bilinear = 1
> dithersub = 1
> dacfilter = 0
> render_threads = 2
> sli = 0
> recompiler = 1
> 
> [Machine]
> cpu_family = pentium_p55c
> cpu_multi = 2.5
> cpu_speed = 166666666
> cpu_use_dynarec = 1
> fpu_type = internal
> machine = 5sg100
> mem_size = 65536
> 
> [Video]
> gfxcard = voodoo3_2k_agp
> video_fullscreen_scale_maximized = 1
> ```
> 
> Tested on WIndows 11.

This seems like a color conversion bug - can you uplaod the VM please?

**Comment by lotharsm** [comment]
> This seems like a color conversion bug - can you uplaod the VM please (I don't need the DVD - I have plenty myself I can use for this - so I just need the hard disk image + nvr folder + config file)?

Sure, thank you - I'll prepare the image in a couple of hours and sent it to you by mail privately.

**Comment by dhrdlicka** [comment]
> I also want to report a problem with 3dfx voodoo 3 3000 emulation (I use SFFT drivers). Namely, in the game Toy Story 2 textures stopped displaying correctly. Unfortunately, I am not able to determine from which build this problem occurs. I am attaching the cfg file and screenshots with this problem https://mega.nz/file/xrJyRC4Y#TqgIfPJhwgBZnsNdj4kowa43UUvnh6beS6DukeSN4X8
> 
> ![Image](https://github.com/user-attachments/assets/b7f1e851-11d8-4f18-99dc-70fd5a42e133)

You are using PCBox, please verify that the issue actually happens on 86Box proper. We do not accept bug reports for PCBox.

**Comment by Kappa971** [comment]
Voodoo needs some love 😢...

<img width="1440" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c7246218-c923-4d55-bf1f-97cf79a3c1b3" />

<img width="1440" height="1080" alt="Image" src="https://github.com/user-attachments/assets/75a1d698-e4a1-4804-981b-2c416fea1132" />

<img width="1440" height="1080" alt="Image" src="https://github.com/user-attachments/assets/7bfaa565-1837-46af-ba28-2c897e27b315" />

I'm sharing some information but this is a long known problem:
Screamer Rally and Screamer 2 with 3dfx Voodoo 1 4mb (It should be 100% compatible with these games, like all 3dfx DOS games and early Windows games), emulated PC: [86box.txt](https://github.com/user-attachments/files/21185627/86box.txt). This happens with both Voodoo recompiler enabled and disabled, and with any number of render threads. 86Box 5.0 New Recompiler build 7235 64 bit, Windows 11.

**Comment by OBattler** [comment]
That was already reported here: https://github.com/86Box/86Box/issues/1575 . Unfortunately, I'm fairly unfamiliar with the Voodoo code, it came from PCem and is more or less a black box to us right now.

**Comment by OBattler** [comment]
It appears to work fine on one of the DOSBox forks: 

![Image](https://github.com/user-attachments/assets/e3d3ef97-c7e7-4f86-8b40-a17cb021a3de) .

So perhaps a code comparison would be in order.

**Comment by Kappa971** [comment]
> It appears to work fine on one of the DOSBox forks:
> 
> ![Image](https://github.com/user-attachments/assets/e3d3ef97-c7e7-4f86-8b40-a17cb021a3de) .
> 
> So perhaps a code comparison would be in order.

I haven't tried DOSBox-X but it works on DOSBox Staging.

**Comment by Cacodemon345** [comment]
You can use Voodoo 2 with Voodoo 2 DOS drivers in the meanwhile to play these games.

**Comment by Kappa971** [comment]
> You can use Voodoo 2 with Voodoo 2 DOS drivers in the meanwhile to play these games.

Using a Voodoo 2, from what I've noticed on 86Box, creates several compatibility issues with Glide games from 1995-1997. For example, Screamer Rally with Voodoo 2 tends to become very unstable or unplayable.
I was only able to get it to work with an old Voodoo 2 glide2x.ovl driver, and you have to limit the memory to 4MB, but even then it's not very stable.
During installation, the game doesn't detect the Voodoo 2 at all (but it detect the Voodoo 1, if present). The solution would be to fix the problems with Voodoo 1 emulation.
The issue mentioned above dates back to 2021, so Voodoo emulation has been broken for at least 4 years.

I want to clarify that I don't pretend anything, I'm just reporting a bug.
I know it's an open source project, a fantastic emulator that people contribute to in their free time and that in the future could even replace real hardware (sooner or later those PCs will die), I know that maybe there are other priorities and that perhaps Voodoo emulation is considered less important than others, but it's still an emulated video card that hasn't worked well for at least 4 years 😅.

**Comment by Cacodemon345** [comment]
Like OBattler said, we don't understand the Voodoo code really well enough to fix the bug. We will fix it if we can find the source of the bug.

This also wasn't the only thing problematic in this emulator; see the mouse/video smoothness issues that were a problem for years until it got fixed. :p

**Comment by Kappa971** [comment]
> Like OBattler said, we don't understand the Voodoo code really well enough to fix the bug. We will fix it if we can find the source of the bug.

In some DOSBox forks like DOSBox Staging Voodoo 1 emulation works, maybe you can start from there.

> This also wasn't the only thing problematic in this emulator; see the mouse/video smoothness issues that were a problem for years until it got fixed. :p

Luckily that's fixed, thanks again 😁.

**Comment by OBattler** [comment]
Screamer Rally on Voodoo 1 is now fixed.

**Comment by eddmanx** [comment]
I checked Extreme Assault again in case the latest change fixed it, but it's still bugged.

OBattler, could you please put a checkmark for the issues that got fixed instead of removing them entirely? That would make it much easier to keep track of closed issues.

**Comment by DSN9990** [comment]
I'm having an issue with the Quake II cutscenes in that it shows a glitch at the top of the window (happens with both Voodoo 1 and Voodoo 2): 

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/cbd9c657-c976-4410-82c1-f2f12f783ac2" />

From what I remember this issue wasn't present before, I think.

**Comment by Cacodemon345** [comment]
@lotharsm Try build 7245 and see if it still happens.

**Comment by DSN9990** [comment]
@Cacodemon345 I also noticed that the brightness control in Quake II doesn't seem to work with both Voodoo 1 and 2 in any way. I tried setting through the Voodoo 2 control panel and it makes no difference so far. I want to change the gamma level in the game since it appears to be too bright with V2, though.

**Comment by Cacodemon345** [comment]
I thought the brightness controls should work.

**Comment by lotharsm** [comment]
> [@lotharsm](https://github.com/lotharsm) Try build 7245 and see if it still happens.

It works, I can't replicate the issue anymore. Great job everyone, thank you!

**Comment by unreal9010** [comment]
@Cacodemon345 could you also take a look at the dots issue that occurs in Grim Fandango, Blood 2 and Shogo when running with Voodoo 2?
The issue only occurs with Voodoo 2 (regardless of what drivers are used) and not with any other card of the Voodoo family.

![Image](https://github.com/user-attachments/assets/9811474f-bb69-4aaa-abe3-c55b9a88174c)

**Comment by Cacodemon345** [comment]
I suspect this is a precision issue.

**Comment by yes897** [comment]
the voodoo 3 also has garbled text on rhcl 7.2

**Comment by DSN9990** [comment]
Hi @Cacodemon345 could you take a look at this minor bug in Star Wars - Shadows of the Empire in voodoo 2 once possible? The font rendering seems to be corrupted when using Voodoo 2, however with Voodoo 1/Voodoo 3/Banshee this does not occur:

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/a8b8643a-2dec-4ad0-9ccc-3b31a4fe8563" />

I know these can't be fixed at the moment, but I'd love to see some minor bugs fixed at least in the Voodoo 2. Thanks for all your support!

**Comment by yes897** [comment]
also voodoo 3/banshee dosent work in caldera openlinux 2.2 but it seems to have worked in a diffrent release according to this article sorry that i dont have any screenshots to share! but, here is the article. https://www.abortretry.fail/p/the-history-of-caldera-part-2

**Comment by Randrianasulu** [comment]
Tested blin live cd in *86Box-Linux-x86_64-b7777.AppImage (On Slackware x64) and yeah same bug still here

https://archive.org/details/blin-livecd

**Comment by DSN9990** [comment]
Hi all again, can some of these issues be fixed right now? I'd love so much to see the voodoo 1/2 more stable for running win95/98 games anyway..

**Comment by OBattler** [comment]
They are going to be fixed when we understand what's causing them.

**Comment by unreal9010** [comment]
Grim Fandango/Hardball 6/Moto Racer menu issues are now fixed thanks to @AITUS95.

**Comment by Kappa971** [comment]
Since build 8091, there is worse performance with Voodoo 1 (I don't know about other 3DFX cards).

**Comment by AITUS95** [comment]
> Since build 8091, there is worse performance with Voodoo 1 (I don't know about other 3DFX cards).

Can you tell me exactly in which games these performance drops occur?

**Comment by Kappa971** [comment]
> > Since build 8091, there is worse performance with Voodoo 1 (I don't know about other 3DFX cards).
> 
> Can you tell me exactly in which games these performance drops occur?

I only tried Screamer Rally. 

Is there a way to tell if Voodoo emulation is running at the same speed as the original card? Because this performance drop (with the overall emulation speed at 100%) makes me question it even with previous 86Box builds (the fps were higher, but was the performance the same as a real Voodoo 1?).

**Comment by AITUS95** [comment]
> > > Since build 8091, there is worse performance with Voodoo 1 (I don't know about other 3DFX cards).
> > 
> > 
> > Can you tell me exactly in which games these performance drops occur?
> 
> I only tried Screamer Rally.
> 
> Is there a way to tell if Voodoo emulation is running at the same speed as the original card? Because this performance drop (with the overall emulation speed at 100%) makes me question it even with previous 86Box builds (the fps were higher, but was the performance the same as a real Voodoo 1?).

You can try other games like unreal or perform some benchmarks with 3dmark 99 to see if the results are consistent with an original voodoo 1, If you change your CPU to a more powerful one, do you notice any improvements?

**Comment by Kappa971** [comment]
> You can try other games like unreal or perform some benchmarks with 3dmark 99 to see if the results are consistent with an original voodoo 1, If you change your CPU to a more powerful one, do you notice any improvements?

These are the 3DMark 99 Max settings (I disabled vsync in Glide and Direct3D modes):
<img width="642" height="576" alt="Image" src="https://github.com/user-attachments/assets/4a98b383-95bf-4bf3-9b40-b7f3691fef90" />

86Box Build 8090, Pentium MMX 233 MHz, 64 MB RAM, Voodoo 1 (2 render threads, dynamic recompiler), Windows 95C:
<img width="642" height="576" alt="Image" src="https://github.com/user-attachments/assets/15a149b5-b57a-4c5c-8403-5dca6523859f" />

86Box Build 8132, Pentium MMX 233 MHz, 64 MB RAM, Voodoo 1 (2 render threads, dynamic recompiler), Windows 95C:
<img width="642" height="576" alt="Image" src="https://github.com/user-attachments/assets/d44cb54a-4f15-45a3-8aa6-386e86b4fbb2" />

In Direct3D there is no performance difference between the pre and post 8090 builds, and also the emulation seems to run faster than the real hardware which has a score of 962/1576: https://www.youtube.com/watch?v=pf2xBazI9j8

I'd be surprised if the performance drop is only for Screamer Rally (a DOS game).

**Comment by AITUS95** [comment]
With the recent changes, the FIFO wake-up happens a bit less often to improve overall performance. Most games benefit from this, but Screamer Rally relies heavily on very frequent wake-ups, so it’s more sensitive to the change. So it's really just a special case, for the rest of the games, the modification is a positive improvement.

**Comment by Kappa971** [comment]
86Box Build 8090, Pentium MMX 233 MHz, 64 MB RAM, Voodoo 1 (2 render threads, dynamic recompiler), Windows 95C, Unreal v226 3dfx:
<img width="642" height="576" alt="Image" src="https://github.com/user-attachments/assets/ca707a3d-6f76-4a0e-acc4-02d7f5ca962f" />

86Box Build 8132, Pentium MMX 233 MHz, 64 MB RAM, Voodoo 1 (2 render threads, dynamic recompiler), Windows 95C, Unreal v226 3dfx:
<img width="642" height="576" alt="Image" src="https://github.com/user-attachments/assets/47236405-0b35-4c9e-ac0c-67fbfc3a6bd7" />

In this video, Screamer Rally is running on Voodoo 1 on real hardware: https://www.youtube.com/watch?v=VuEgytA2uoE
GitHub won't let me upload the video I recorded of Screamer Rally running on 86Box, but I can tell you it runs at least 10 fps slower on post-8090 builds than on real hardware or 86Box build 8090.

**Comment by Kappa971** [comment]
In summary, the post-build 8090 changes to the Voodoo 1 were supposed to improve performance (optimize emulation on the host machine?). 3DMark 99 (Direct3D) and Unreal (Glide) show that performance remained pretty much the same, except for a few games (in this case, Screamer 2 and Screamer Rally), where performance significantly degraded.
I think these changes should be revised or reverted to restore performance, but this is just my opinion.

**Comment by OBattler** [comment]
There are games which actually perform better now, as in, the emulator no longer goes below 100% while it used to.

**Comment by Kappa971** [comment]
> There are games which actually perform better now, as in, the emulator no longer goes below 100% while it used to.

In my case, the emulation wouldn't go below 100% with old builds (I won't go beyond a Pentium MMX 200/233 MHz because the R7 5700x definitely wouldn't be capable).
Now, some games run worse than before (Screamer 2 and Screamer Rally run at least 10 fps slower than the old builds with 100% emulation speed), so... I don't know, I don't see any improvements with my machine.
You can see my benchmarks and videos (not mine) on real hardware above showing the Voodoo 1 in action.

**Comment by Kappa971** [comment]
I uploaded two short videos to OneDrive to demonstrate the performance drop:
https://1drv.ms/u/c/0c10fb71237f40c4/IQBKzj5y8PftQb2bRzpYbNgKAfP8-42byygm8BH5NiIF-ZI?e=EyHPpk

**Comment by Randrianasulu** [comment]
... as TDE (KDE 3.5 fork) user I tend to suggest "add it as user-tunable parameter".

**Comment by Kappa971** [comment]
> ... as TDE (KDE 3.5 fork) user I tend to suggest "add it as user-tunable parameter".

If developers are skeptical about reverting the previous behavior (despite the evidence I've shared, I don't see any evidence of those who say the opposite 😅), it might be a good compromise to add a new option that restores the old 86Box behavior and can make these games work properly with Voodoo 1 (or find another solution).
The problem exists, I hope it gets solved.

**Comment by Cacodemon345** [comment]
Lands of Lore III issue fixed since https://github.com/86Box/86Box/commit/a1b15156612aa6fa3d5bfe89eaaeb3053ce4a8c0.

**Comment by unreal9010** [comment]
> > ... as TDE (KDE 3.5 fork) user I tend to suggest "add it as user-tunable parameter".
> 
> If developers are skeptical about reverting the previous behavior (despite the evidence I've shared, I don't see any evidence of those who say the opposite 😅), it might be a good compromise to add a new option that restores the old 86Box behavior and can make these games work properly with Voodoo 1 (or find another solution). The problem exists, I hope it gets solved.

86Box is about accuracy. Currently, the Voodoo cards do not yet utilize a timer which is why you're getting much higher fps in most games than you would on a real machine (that applies to Screamer as well).
Below (see picture) is an example of Unreal benchmark tested on different configurations equipped with Voodoo 2. As you can see, K6-2 300 achieves only 34 fps in 640x480 so there's no way in hell that you could reach 38 fps on a real Pentium MMX 233 with a Voodoo 1 card. Were that the case, nobody would be buying Voodoo2 back in the day. 

Even your 3D Mark 99 results are a bit too high when compared to the real deal. Here is an example of 3DM99 benchmark results with Voodoo 3 3000 and PMMX 233. As you can see, that card scores 1298 3D Marks and 1596 3D CPU Marks.
https://www.dosdays.co.uk/topics/Manufacturers/3dfx/3dfx_voodoo3_3000.php

 

![Image](https://github.com/user-attachments/assets/f35b2ad9-0b7a-40f5-9c1b-f38b0e787d3c)

**Comment by OBattler** [comment]
@Kappa971 I'm not skeptical of the problem. The person who did the fix said he will look into it as soon as he gets back home, so please be patient.

**Comment by OBattler** [comment]
Screemer Rally is down from 30 fps to 13 fps on a Pentium MMX 233 MHz, this is definitely strange. The YouTube video is definitely smoother, despite being recorded on the same hardware.

**Comment by Kappa971** [comment]
> [@Kappa971](https://github.com/Kappa971) I'm not skeptical of the problem. The person who did the fix said he will look into it as soon as he gets back home, so please be patient.

No problem.

> Screemer Rally is down from 30 fps to 13 fps on a Pentium MMX 233 MHz, this is definitely strange. The YouTube video is definitely smoother, despite being recorded on the same hardware.

Exactly... and if you try the build 8090, you'll get performance closer to real hardware. As you can see, I'm not crazy 😆

Anyway, I explained the problem, I won't bore you anymore.

**Comment by OBattler** [comment]
But in the video, the CPU is overclocked to 262 MHz (75 MHz FSB), so that's also going to have some effect.

> Exactly... and if you try the build 8090, you'll get performance closer to real hardware. As you can see, I'm not crazy 😆

We do not have any measurement from real hardware, though, nor any video recording from real hardware on a non-overclocked Pentium MMX 233 MHz. In addition, the chipset supports a maximum bus speed of 66 MHz so in this case, even the Voodoo 1 itself is being overclocked because the PCI bus is simply FSB divided by 2, so there's an unusual 37.5 MHz PCI bus here.

**Comment by OBattler** [comment]
And I found a user on the DOS Gaming subreddit who tested Screamer Rally on a real Pentium MMX 200 MHz and Voodoo 1: https://www.reddit.com/r/dosgaming/comments/1j35sz5/why_does_screamer_racing_game_run_so_badly_86box/ .

> a 200Mhz intel with a voodoo 1. maybe 10-15 fps

it sort of crashes with a voodoo2, but can find patched executables that work, but fps remains the same

Which to me, indicates that the ~13 fps observed on 86Box is within the real hardware range, and the YouTube video has it smoother due to the overclocking.

There's also this from another user in the same thread:

> On real hardware you needed a pentium 120mhz or higher before the low res exe ran at around full speed.  I have a pentium 233 and the high res exe runs to slowly for me to enjoy it (the low res exe runs perfectly).

And the YouTube video does look to me like it's in a lower resolution than your 86Box recording, which would further explain it.

So actually, on build 8090, it was too fast, and now it's closer to the real hardware.

**Comment by Kappa971** [comment]
> And I found a user on the DOS Gaming subreddit who tested Screamer Rally on a real Pentium MMX 200 MHz and Voodoo 1: https://www.reddit.com/r/dosgaming/comments/1j35sz5/why_does_screamer_racing_game_run_so_badly_86box/ .
> 
> > a 200Mhz intel with a voodoo 1. maybe 10-15 fps

I didn't notice the overclock in that video, my fault.
Anyway, this user's answer isn't necessarily true. Without solid evidence, it's difficult to say.

> it sort of crashes with a voodoo2, but can find patched executables that work, but fps remains the same

This is true, I tested it on 86Box and with a Voodoo 2 it only worked with a specific driver version and limiting the video memory. All tedious stuff... the game officially supports only Voodoo 1.

> Which to me, indicates that the ~13 fps observed on 86Box is within the real hardware range, and the YouTube video has it smoother due to the overclocking.

It's possible but I've found this video of Screamer 2 (this game also has slow performance similar to Screamer Rally with the latest 86Box builds): https://www.youtube.com/watch?v=7EaVzIFm4iM

> There's also this from another user in the same thread:
> 
> > On real hardware you needed a pentium 120mhz or higher before the low res exe ran at around full speed.  I have a pentium 233 and the high res exe runs to slowly for me to enjoy it (the low res exe runs perfectly).
>
> And the YouTube video does look to me like it's in a lower resolution than your 86Box recording, which would further explain it.

I think the person who answered didn't understand that they were talking about the Voodoo version.
The Voodoo version has only one executable and the resolution in the YouTube videos (the one with the overclocked CPU and the Screamer 2 one above) should be 640x480 like in my video, I don't think it's lower.
 
> So actually, on build 8090, it was too fast, and now it's closer to the real hardware.

I'm still skeptical about this, especially if the answers only come from reddit (which can be a jungle of conflicting thoughts)... the current performance of Screamer Rally on 86Box with Voodoo 1 seems too low even for 1997 (if we're talking about 3D accelerated games for Voodoo 1), but at this point I'm not ruling anything out.

**Comment by Kappa971** [comment]
Maybe this?
https://www.youtube.com/watch?v=pq5kV8Tdvik

or these:
https://x.com/hajek_jaromir/status/1799644886456775094
https://www.youtube.com/watch?v=ry488qnSd4w
https://www.youtube.com/watch?v=VkzO2w6EqK4

In these videos, Screamer 2/Rally with Voodoo 1 definitely runs at 25+ fps.

**Comment by eddmanx** [comment]
> > it sort of crashes with a voodoo2, but can find patched executables that work, but fps remains the same
> 
> This is true, I tested it on 86Box and with a Voodoo 2 it only worked with a specific driver version and limiting the video memory. All tedious stuff... the game officially supports only Voodoo 1.

There is an official patch for voodoo 2, `sr3dfx2.zip`. I copied the glide2x.ovl from a randomly chosen driver, 3.01.01, to the game's directory and it works fine, even with the memory set to max. The fps fluctuates in the 25-35 range.

**Comment by AITUS95** [comment]
#6568 The regression for glide games like Screamer Rally and Unreal has been resolved.

**Comment by Kappa971** [comment]
> [#6568](https://github.com/86Box/86Box/pull/6568) The regression for glide games like Screamer Rally and Unreal has been resolved.

Performance has improved but in my opinion we're not there yet, they're still inferior to build 8090.
@OBattler mentioned that it's possible that the Voodoo 1 emulations were previously running too fast, but I've found other Screamer 2/Rally videos where you can see the performance on real hardware: https://github.com/86Box/86Box/issues/4483#issuecomment-3652387565

Additionally, two other issues:
1. In Screamer 2, you may notice a new issue where parts of the game world load late or flicker. This happens with build 8138 and later, but I think it's due to changes made in build 8136 (builds 8136 and 8137 crash when starting a game): https://1drv.ms/u/c/0c10fb71237f40c4/IQCYKu7tR6BvRYecB_GN6MTNAbZXxmtMPU1O21FKUTK10TU?e=yrdT4W
2. Running the Unreal timedemo (it had no performance issues) I noticed some small drops in emulation speed below 100%. This happens with build 8138 and later, like Screamer 2.

In summary
- Build 8091 caused regressions with Screamer 2 and Screamer Rally.
- Builds 8136/8138 caused slower emulation speeds in some cases and caused the game world to flicker in Screamer 2.

I think changes like this need to be tested more thoroughly.

**Comment by Cacodemon345** [comment]
Build 8138 introduced changes to the new dynarec to better handle self-modifying code.

**Comment by Cacodemon345** [comment]
https://github.com/86Box/86Box/commit/41ed34c67f5baa875eb74bbdeae36f47e8bf57de

Voodoo 2 black/white dot bugs are now fixed.

**Comment by unreal9010** [comment]
Grim Fandango/Shogo/Blood 2 dots issue with Voodoo 2 is now fixed!

**Comment by mr-falafel** [comment]
Just thought I'd chime in and mention that I have Pentium III machine with a Voodoo3 3500 installed. The PIII is a 1000Mhz Coppermine, which I know effects the performance of the Voodoo greatly. Regardless, I would be happy to test behaviour/performance of software, if it helps.

**Comment by AITUS95** [comment]
> Just thought I'd chime in and mention that I have Pentium III machine with a Voodoo3 3500 installed. The PIII is a 1000Mhz Coppermine, which I know effects the performance of the Voodoo greatly. Regardless, I would be happy to test behaviour/performance of software, if it helps.

Could you test glover and 3dmark99 with single framebuffer?

**Comment by DSN9990** [comment]
I'm getting massive slowdowns in NFS Porsche Unleashed.
What this could be? I'm not mentioning the emulator's speed, it is the game's FPS.
I'm running it with a Voodoo 2 SLI setup and a PII 300 cpu.

**Comment by AITUS95** [comment]
> I'm getting massive slowdowns in NFS Porsche Unleashed. What this could be? I'm not mentioning the emulator's speed, it is the game's FPS. I'm running it with a Voodoo 2 SLI setup and a PII 300 cpu.

What are your current graphics settings in the game?

**Comment by eddmanx** [comment]
> I'm getting massive slowdowns in NFS Porsche Unleashed. What this could be? I'm not mentioning the emulator's speed, it is the game's FPS. I'm running it with a Voodoo 2 SLI setup and a PII 300 cpu.

Which 86box build?

EDIT:

Try build 8305.

**Comment by mr-falafel** [comment]
> > Just thought I'd chime in and mention that I have Pentium III machine with a Voodoo3 3500 installed. The PIII is a 1000Mhz Coppermine, which I know effects the performance of the Voodoo greatly. Regardless, I would be happy to test behaviour/performance of software, if it helps.
> 
> Could you test glover and 3dmark99 with single framebuffer?

Certainly. I won't have a chance now until next weekend or the week after but I'll get back to you as soon as I'm able.
edit: Also, apologies that I didn't see your message until now. Somehow missed the notification from github...

**Comment by DSN9990** [comment]
> > I'm getting massive slowdowns in NFS Porsche Unleashed. What this could be? I'm not mentioning the emulator's speed, it is the game's FPS. I'm running it with a Voodoo 2 SLI setup and a PII 300 cpu.
> 
> Which 86box build?
> 
> EDIT:
> 
> Try build 8305.

I'm currently using build 8360, and the in-game graphic settings are all bumped to the maximum. Maybe it is due to this?

**Comment by OBattler** [comment]
NFS Porsche Unleashed is from 2000, so it's unlikely to run at full speed on with maxed out settings on a Pentium II and Voodoo 2.

**Comment by DSN9990** [comment]
> NFS Porsche Unleashed is from 2000, so it's unlikely to run at full speed on with maxed out settings on a Pentium II and Voodoo 2.

ok, but I have other games from circa 1999-2000 (such as Quake III) and they run better than NFSPS, so I do not know why it lags so much.

What are the recommended specs for running NFSPS at full graphics detail without lagging?

**Comment by OBattler** [comment]
Try a Voodoo 3.

**Comment by AITUS95** [comment]
Tested NFS Porsche Unleashed right now with Pentium 2 Deschutes 300mhz and Voodoo SLI, the game has some slowdown at 800x600 resolution but still very playable in my opinion, the frame rate can improve a lot if you set a resolution to 640x480 and this is a sign that the system is struggling a lot, so it's very similar to a real situation which could very likely have occurred on a real system as well.

**Comment by DSN9990** [comment]
OK, but I noticed that the game slows down even with 640x480 resolution, especially on the Normandie track, where it lags a lot

**Comment by AITUS95** [comment]
> OK, but I noticed that the game slows down even with 640x480 resolution, especially on the Normandie track, where it lags a lot

It's not for me, the game runs very smooth at that resolution, how many threads do you have set?

**Comment by DSN9990** [comment]
> > OK, but I noticed that the game slows down even with 640x480 resolution, especially on the Normandie track, where it lags a lot
> 
> It's not for me, the game runs very smooth at that resolution, how many threads do you have set?

I have 2 threads set up for my Voodoo 2 SLI

**Comment by AITUS95** [comment]
You should set them to 4 if your system allows it, for me with 4 threads I have no problems.

**Comment by DSN9990** [comment]
OK, I will check soon, but does it really work properly with 4 threads set up? I recall that setting 4 threads for any Voodoo card causes glitches to arise in certain games such as NFSIISE, so maybe this bug is already fixed?

**Comment by AITUS95** [comment]
Everything looks good graphically on my side. Also, thanks to PR #6728, the Voodoo 1 and 2 timings feel much better. Some games that used to run way too fast are now playing at a more reasonable speed.

**Comment by eddmanx** [comment]
> > 
> > 
> > Which 86box build?
> > EDIT:
> > Try build 8305.
> 
> I'm currently using build 8360, and the in-game graphic settings are all bumped to the maximum. Maybe it is due to this?

Why are you ignoring the second part of my message?

**Comment by DSN9990** [comment]
Ok, I tried the game again right now however it still slows down in the Normandie track, with maximum graphic settings, and NFS High Stakes seems to be glitched with 4 threads set.

**Comment by DSN9990** [comment]
@Cacodemon345 could you try to fix the black loading screen issue in Tomb Raider III when using Voodoo 1 if possible? Since you already fixed some outstanding bugs in the Voodoo 2, I hope you will be able to fix this one easily as well. And TR3 looks so ugly with this bug on VG. Thanks for your support!

**Comment by OBattler** [comment]
Voodoo 3 render glitch in Microsoft Bob: https://github.com/86Box/86Box/issues/6971 .

**Comment by Froakiein2022** [comment]
Tested Moto Racer 2 (patch 1.34 applied) with Voodoo 2 SLI (2 render threads) and Pentium MMX 233 emulated system on 86Box build 9674 (Old Recompiler):
<img width="1920" height="904" alt="Image" src="https://github.com/user-attachments/assets/72647f91-74fb-494d-93dd-a415cbac7976" />

There is an issue where each bike (except the default blue bike) in the race during gameplay would show white textures for all parts (except for the wheels):
<img width="1920" height="904" alt="Image" src="https://github.com/user-attachments/assets/2db1c006-463d-4c03-913c-d25ce923f571" />
This issue persists, even when I set the resolution down to 640 x 480 and the detail level down to very low.

This issue does not happen in the menu for selecting bikes, where each bike shows the correct textures.

Here is the info for the Voodoo 2 driver that I used:
<img width="1920" height="904" alt="Image" src="https://github.com/user-attachments/assets/8de34e43-1945-4ff9-990e-ddf903be322e" />

**Comment by eddmanx** [comment]
Don't apply the patch and it's fine.

**Comment by Froakiein2022** [comment]
I've just tried Moto Racer 2 without installing the patch. That solved the issue.

**Comment by pankoza2-pl** [comment]
Voodoo-related issue: The 3Dfx Voodoo Banshee AGP driver installer found on a Gateway OEM CD fails to detect the card

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/7d2e8f74-2216-4b4f-aafc-ef5f162a5fdd" />

**Comment by pankoza2-pl** [comment]
> Voodoo-related issue: The 3Dfx Voodoo Banshee AGP driver installer found on a Gateway OEM CD fails to detect the card
> 
> <img alt="Image" width="640" height="480" src="https://private-user-images.githubusercontent.com/77279607/641781680-7d2e8f74-2216-4b4f-aafc-ef5f162a5fdd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODc3NzQxMjYsIm5iZiI6MTc4Nzc3MzgyNiwicGF0aCI6Ii83NzI3OTYwNy82NDE3ODE2ODAtN2QyZThmNzQtMjIxNi00YjRmLWFhZmMtZWY1ZjE2MmE1ZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODI2VDE5NTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYmNiMzcxZTQ0NTNkOTI3MGI4YTE4M2RkNzNlZWNjMTE5YTQ3ZDI1ZTJkNTJmYWRjNzFmNGIyNWRmOWY3YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.FjeJ0rdwCJGv-e2PtHuomBJb1wHkv51w2nyAMzQnfNE">

<img width="720" height="400" alt="Image" src="https://github.com/user-attachments/assets/b2381533-4893-4d92-b5f7-64ea9ca99ef4" /> 

This looks to be caused by 86Box incorrectly using the VBIOSes of the PCI Voodoo Banshee on the AGP card

**Comment by eddmanx** [comment]
> I have real Voodoo 1 / Voodoo 2 / Voodoo 3 Graphics card. I'm willing to help testing if you provide the game.

@kkwpsv Are you still ok with doing a few tests?

**Comment by kkwpsv** [comment]
> > I have real Voodoo 1 / Voodoo 2 / Voodoo 3 Graphics card. I'm willing to help testing if you provide the game.
> 
> [@kkwpsv](https://github.com/kkwpsv) Are you still ok with doing a few tests?

Yes. I'm still ok.

**Comment by eddmanx** [comment]
> Yes. I'm still ok.

Can you test Disney-Pixar Toy Story 2, see if the wall texture looks correct? The recording below is with a Voodoo 3, driver 1.07, Windows 98 SE. Regarding the game, how can I contact you outside of github? Are you on the 86box discord server?

https://github.com/user-attachments/assets/0e14f4fb-02fc-48c2-887b-75b46e530c2a

**Comment by kkwpsv** [comment]
> Can you test Disney-Pixar Toy Story 2, see if the wall texture looks correct? The recording below is with a Voodoo 3, driver 1.07, Windows 98 SE. Regarding the game, how can I contact you outside of github? Are you on the 86box discord server?

OK. But wait until I have some free time in a few days. I need to reassemble the computer.
Due to network issues, I rarely use discord. I have joined the 86box discord server now. You can contact me via discord. I'll be keeping an eye on it.
